name: Greet on Issue or PR

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
          gh --version

      - name: Greet User
        run: |
          GREETING="Hello, @$USER! Thank you for your contribution." # Modify this message as needed
          echo "Greeting: $GREETING"
          gh issue comment ${{ github.event.issue.number }} --body "$GREETING"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
